from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Float, ForeignKey, Text, func
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.models.enums import FindingStatus, Severity

if TYPE_CHECKING:
    from app.models.agent_run import AgentRun


class AgentFinding(Base):
    """
    AgentFinding model representing structured threat conclusions generated by swarm agents.
    """
    __tablename__ = "agent_findings"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    agent_run_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("agent_runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    finding: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    severity: Mapped[Severity] = mapped_column(
        SQLEnum(*(e.value for e in Severity), name="severity_enum"),
        nullable=False,
    )
    indicators: Mapped[dict] = mapped_column(JSONB, nullable=False)
    evidence: Mapped[dict] = mapped_column(JSONB, nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    external_refs: Mapped[dict] = mapped_column(JSONB, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    status: Mapped[FindingStatus] = mapped_column(
        SQLEnum(*(e.value for e in FindingStatus), name="finding_status_enum"),
        nullable=False,
    )

    # Relationships
    agent_run: Mapped[AgentRun] = relationship(
        "AgentRun",
        back_populates="findings",
    )
