"""initial schema

Revision ID: cf25626f42d2
Revises: 
Create Date: 2026-08-19 15:52:27.517800

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf25626f42d2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_risk_score', sa.Float(), nullable=True),
    sa.Column('final_severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum'), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investigations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('skipped', 'running', 'done', 'failed', name='agent_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_agent_runs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_table('conflict_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_a', sa.Text(), nullable=False),
    sa.Column('agent_b', sa.Text(), nullable=False),
    sa.Column('conflict_type', sa.Text(), nullable=False),
    sa.Column('resolution_rule', sa.Text(), nullable=False),
    sa.Column('resolution_outcome', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_conflict_logs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflict_logs'))
    )
    op.create_table('evidence_inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('modality', sa.Enum('text', 'url', 'qr', 'image', 'voice', name='modality_enum'), nullable=False),
    sa.Column('raw_content_ref', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_inputs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_inputs'))
    )
    op.create_table('investigation_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_reports_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_reports'))
    )
    op.create_table('rag_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('CERT-In', 'RBI', 'Scam-Intel', name='source_type_enum'), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_rag_citations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_citations'))
    )
    op.create_table('risk_breakdown',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_risk_breakdown_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_breakdown'))
    )
    op.create_table('agent_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity_enum'), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ok', 'degraded_fallback', 'failed', 'skipped', name='finding_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_findings_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_findings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_findings')
    op.drop_table('risk_breakdown')
    op.drop_table('rag_citations')
    op.drop_table('investigation_reports')
    op.drop_table('evidence_inputs')
    op.drop_table('conflict_logs')
    op.drop_table('agent_runs')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
